% This file is automatically generated by updateModel.m from the NFkB whole-cell spreadsheet.
% Model URL: multi-stimulus NFkB.xlsx

%% Section 1: Declaration/initialization (code from ode_init.m)
function delta = nfkbOde_norxn(t,x,ode_options,v)
% - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
% delta = nfkbOde(t,x,ode_options,v)
% - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
% Full NFkB ODE model - stiff system, designed to be solved using ode15 (see this function's help file to set
% options).  
% In phase 1 (v.PHASE == 1),simulation is run w/o stimulus, until convergence to initialize steady-state,
% - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

% Set the persistent variable that discrete-delay reactions refer to
% persistent DELAY;
% if isempty(t)
%     % The sim function calls the ode function once without arguments to reset persistent variables
%     sz = 5000; % Size of total delay memory - if DELAYS.idx exceeds this, function will throw error
%     DELAY.t = zeros(sz;
%     DELAY.nfkb = zeros(sz; % increase if getting errors
%     DELAY.ikbat = zeros(sz; % increase if getting errors
%     DELAY.idx     = 1; % index (starts at 1)
%     return;
% end


% Slice parameters, get previous concentrations
p = v.PARAMS;
delta = zeros(size(x));

params1 = 1; % induced IKK activation (general)
params2 = 2e-05; % basal IKK activation
params3 = 2; % IKK inhibition (IKK cycling)
params4 = 18; % IKK renewal (IKK cycling)
params5 = 5e-07; % basal IkBa mRNA synthesis
params6 = 6e-05; % induced IkBa mRNA synthesis
params6n2 = 2.938; % Hill coefficient for mRNA syn
params6n3 = 0.1775; % EC50 for mRNA syn
params6n4 = 14; % mRNA transcription/processing/maturation delay
params7 = 0.0577623; % IkBa mRNA degradation
params8 = 30; % IkBa mRNA translation
params8n2 = 1; % Translation/folding delay
params9 = 0.0225; % nuclear import of IkBa
params9n2 = 3.5; % Volume scale: cytoplasmic/nuclear volume
params10 = 0.6; % nuclear import of NFkB
params10n2 = 3.5; % Volume scale: cytoplasmic/nuclear volume
params11 = 0.1575; % nuclear export of IkBa
params11n2 = 0.285714; % Volume scale: nuclear/cytoplasmic volume
params12 = 0.042; % nuclear export of NFkB
params12n2 = 0.285714; % Volume scale: nuclear/cytoplasmic volume
params13 = 0; % nuclear import of IkBa-NFkB
params13n2 = 3.5; % Volume scale: cytoplasmic/nuclear volume
params14 = 0.828; % nuclear export of IkBa-NFkB
params14n2 = 0.285714; % Volume scale: cytoplasmic/nuclear volume
params15 = 0.0770164; % degradation of IkBa
params16 = 0.0770164; % degradation of IkBa (nuc)
params17 = 200; % IkBa-NFkB association
params18 = 200; % IkBa-NFkB association (nuc)
params19 = 0.008; % IkBa-NFkB dissociation
params20 = 0.008; % IkBa-NFkB dissociation (nuc)
params21 = 190; % IKK-IkBa-NFkB association
params22 = 190; % IKK-IkBa association
params23 = 38; % IKK-IkBa-NFkB dissociation
params24 = 38; % IKK-IkBa dissociation
params25 = 2; % Phosphorylation/degradation of complexed IkBa
params26 = 2; % Phosphorylation/degradation of IkBa
params27 = 8.75; % CD14-LPS association
params27n2 = 0.001; % Scale for external (media) vs. internal (cellular) volumes
params28 = 0.07; % CD14-LPS dissociation
params28n2 = 0.001; % Scale for external (media) vs. internal (cellular) volumes
params29 = 0.00112; % CD14 synthesis
params30 = 0.000878; % CD14 degradation
params31 = 5.543; % Assocation of LPS and CD14 in plasma membrane
params32 = 0.0277; % Disassociation of TLR4LPS in the plamsa membrane
params33 = 5.543; % Assocation of LPS and CD14 in the endosome
params34 = 0.0277; % Disassociation of TLR4LPS in the endosome
params35 = 5.25e-05; % Synthesis rate of TLR4
params36 = 0.065681; % Induced endocytosis of CD14
params37 = 0.04; % Recycling of CD14
params38 = 0.028028; % Constitutive endocytosis of TLR4
params39 = 0.5; % Recycling of TLR4
params40 = 0.065681; % Induced endocytosis of activated CD14-TLR4
params41 = 0.04; % Recycling of CD14-TLR4
params42 = 0.07; % Degradation of CD14-LPS
params43 = 0.0653; % Degradation of TLR4
params44 = 0.012; % Degradation of activated TLR4-LPS
params45 = 150; % Activation of MyD88
params45n2 = 3; % Hill coefficient for MyD88 activation
params45n3 = 0.012448; % EC50 for MyD88 activation
params46 = 2600; % Deactivation of MyD88
params47 = 6; % Activation of TRIF
params48 = 0.2; % Deactivation of TRIF
params49 = 30; % Activation of TRAF6 by MyD88
params50 = 0.4; % Activation of TRAF6 by TRIF
params51 = 0.125; % Deactivation of TRAF6
params52 = 0.105; % Activation of TAK1 by TRAF6
params53 = 0.0116; % TNF degradation
params54 = 8.224e-06; % TNFR synthesis
params55 = 0.02384; % TNFR degradation
params56 = 1100; % Capture of TNF
params56n2 = 0.001; % Scale for external (media) vs. internal (cellular) volumes
params57 = 0.021; % Release of TNF
params57n2 = 0.001; % Scale for external (media) vs. internal (cellular) volumes
params58 = 0.125; % Internalization/degradation of complexed TNFR
params59 = 34.08; % Association of TRAF2/RIP1 with receptor trimer
params60 = 0.03812; % Dissociation of TRAF2/RIP1 with receptor trimer
params61 = 0.125; % Internalization/degradation of complexed TNFR
params62 = 1.875; % Activation of complexed TNFR
params63 = 320.3; % Inactivation of complexed TNFR
params64 = 0.125; % Internalization/degradation of complexed TNFR
params65 = 1889; % Activation of TAK1 by C1
params66 = 0.5188; % Inactivation of TAK1
params67 = 18.79; % Activation of IKK by TAK1
params67n2 = 2; % Hill coefficient for IKK activation
params67n3 = 0.001116; % EC50 for mRNA syn
params68 = 1e-06; % TLR1/2 synthesis
params69 = 0.0004; % TLR1/2 degradation
params70 = 1; % Association of CD14 and lipoprotein
params70n2 = 0.001; % Scale for external (media) vs. internal (cellular) volumes
params71 = 1.8; % Dissociation of CD14/lipoprotein
params71n2 = 0.001; % Scale for external (media) vs. internal (cellular) volumes
params72 = 5.543; % NaN
params73 = 0.07; % Degradation of CD14-P3CSK
params74 = 0.02; % NaN
params75 = 0.001; % Degradation of ligand/receptor
params76 = 150; % Activation of MyD88
params76n2 = 3; % Hill coefficient for MyD88 activation
params76n3 = 0.0032; % EC50 for MyD88 activation
params77 = 3e-06; % TLR3 synthesis
params78 = 0.0007; % TLR3 degradation
params79 = 0.04; % Poly(I:C) internalization
params79n2 = 0.03; % EC50 for poly(I:C) internalization
params79n3 = 1; % Hill coefficient for poly(I:C) internalization
params79n4 = 0.001; % NaN
params80 = 0.04; % NaN
params80n2 = 0.001; % Poly(I:C) release
params81 = 0.5; % NaN
params82 = 0.025; % NaN
params83 = 0.0007; % Bound poly(I:C)-TLR3 degradation
params84 = 20; %  Activation of TRIF by bound TLR3
params85 = 2e-06; % TLR9 synthesis
params86 = 0.0004; % TLR9 degradation
params87 = 0.0004; % TLR9 degradation (N terminus fragment)
params88 = 0.015; % CpG internalization
params88n2 = 0.5; % EC50 for CpG internalization
params88n3 = 1; % Hill coefficient for CpG internalization
params88n4 = 0.001; % NaN
params89 = 0.028; % CpG exchange from endosome
params89n2 = 0.001; % NaN
params90 = 3; % Ligand-receptor association
params91 = 0.5; % Ligand-receptor dissociation
params92 = 3; % Mediated degrdadation of bound TLR9
params93 = 0.0016; % Bound CpG-TLR9 degradation
params94 = 200; % Activation of MyD88
params94n2 = 3; % Hill coefficient for MyD88 activation
params94n3 = 0.0032; % EC50 for MyD88 activation
params95 = 0; % degradation of NF-kB (used as proxy for irreversible sequestration)
params96 = 0.33; % IkBat to IkBat_cas1 transformation rate
params97 = 0.33; % IkBat_cas1 to IkBat_cas2 transformation rate
params98 = 0.0577623; % IkBat_cas2 mRNA degradation
params99 = 0.25; %production rate from  NFkBn to NFkBn_cas1
params100 = 0.25; %transformation rate from NFkBn_cas1 to NFkBn_cas2
params101 = 0.25; %degradation rate of NFkBn_cas2


%% Section 2: Unpack species
stim = x(1);
IkBa = x(2);
IkBan = x(3);
IkBaNFkB = x(4);
IkBaNFkBn = x(5);
IkBat = x(6);
IKKIkBaNFkB = x(7);
IKKIkBa = x(8);
NFkB = x(9);
NFkBn = x(10);
IKK_off = x(11);
IKK = x(12);
IKK_i = x(13);
LPS = x(14);
CD14 = x(15);
CD14LPS = x(16);
CD14LPSen = x(17);
TLR4 = x(18);
TLR4en = x(19);
TLR4LPS = x(20);
TLR4LPSen = x(21);
MyD88_off = x(22);
MyD88 = x(23);
TRIF_off = x(24);
TRIF = x(25);
TRAF6_off = x(26);
TRAF6 = x(27);
TNF = x(28);
TNFR = x(29);
TNFR_TNF = x(30);
TTR = x(31);
C1_off = x(32);
C1 = x(33);
TAK1_off = x(34);
TAK1 = x(35);
Pam3CSK = x(36);
TLR2 = x(37);
CD14_P3CSK = x(38);
TLR2_P3CSK = x(39);
polyIC = x(40);
polyIC_en = x(41);
TLR3 = x(42);
TLR3_polyIC = x(43);
CpG = x(44);
CpG_en = x(45);
TLR9 = x(46);
TLR9_CpG = x(47);
TLR9_N = x(48);
IkBat_cas1=x(49);
IkBat_cas2=x(50);
NFkBn_cas1=x(51);
NFkBn_cas2=x(52);



%% Section 3: Calculate delays (code from ode_delay.m)
% Initialize/calculate delays for discrete-delay reactions
% (Delays are manually set - if reactions are rearranged such that tau indicies change, this code 
% must be reset)

% Create a cache of previous species values for transcription/translation delays.
% NFkBn_tau6   = NFkBn;
% IkBat_tau8   = IkBat;
% if v.PHASE ~= 1
%     % Match current timepoint into t vector - append, if necessary
%     idx = find(DELAY.t(1:DELAY.idx)>=t,1,'first');
%     if isempty(idx)
%         idx = DELAY.idx+1;
%     end
%     DELAY.t(idx) = t;
%     DELAY.idx = idx;
%     DELAY.nfkb(DELAY.idx) = NFkBn;
%     DELAY.ikbat(DELAY.idx) = IkBat;
%     if DELAY.idx > length(DELAY.t)
%         error(['Delay index out of range: increase memory size (line 13 - ',...
%             'sz = ',num2str(length(DELAY.t)),';). Reached t = ',num2str(DELAY.t(end))])
%     end
% 
%     % 1) IkBa mRNA transcription/processing delay (RXN 6)
%     tau = params6n4;
%     if tau > 0  % IkBa inducible txn delay
%         if t > tau
%             NFkBn_tau6 = ...
%                 interp1(DELAY.t(1:DELAY.idx-1),...
%                         DELAY.nfkb(1:DELAY.idx-1),t-tau);
%         else
%             NFkBn_tau6 = ...
%                 DELAY.nfkb(1); % 1st index is the steady-state value
%         end
%     end
%     
%     % 2) IkBa protein translation/maturation delay (RXN 8)
%     tau = params8n2;
%     if tau > 0  % IkBb inducible txn delay
%         if t > tau
%             IkBat_tau8 = ...
%                 interp1(DELAY.t(1:DELAY.idx-1),...
%                         DELAY.ikbat(1:DELAY.idx-1),t-tau);
%         else
%             IkBat_tau8 = ...
%                 DELAY.ikbat(1); % 1st index is the steady-state value
%         end
%     end
% end

% Pulsed stimulus (ode_options.PULSE_TIME) - if time value is greater than pulse length, set external stimuli to zero
if isfield(v,'PULSE_TIME') && (t > v.PULSE_TIME)
    TNF = 0;
    LPS = 0;
    polyIC = 0;
    Pam3CSK = 0;
    CpG = 0;
    stim=0;
end



%% Section 4: Set reaction rates
% params1 * stim * IKK_off = params1 * stim * IKK_off;
% params2 * IKK_off = params2 * IKK_off;
% params3 * IKK = params3 * IKK;
% params4 * IKK_i = params4 * IKK_i;
% params5 = params5;
% params6 * (NFkBn_cas2.^params6n2)/( (NFkBn_cas2.^params6n2) + (params6n3.^params6n2) ) = params6 * (NFkBn_cas2.^params6n2)/( (NFkBn_cas2.^params6n2) + (params6n3.^params6n2) );
% params7 * IkBat = params7 * IkBat;
% params8 * IkBat_cas2 = params8 * IkBat_cas2;
% params9 * IkBa = params9 * IkBa; % *params9n2 
% params10 * NFkB = params10 * NFkB;
% params11 * IkBan = params11 * IkBan;
% params12 * NFkBn = params12 * NFkBn;
% params13 * IkBaNFkB = params13 * IkBaNFkB;
% params14 * IkBaNFkBn = params14 * IkBaNFkBn;
% params15 * IkBa = params15 * IkBa;
% params16 * IkBan = params16 * IkBan;
% params17 * IkBa * NFkB = params17 * IkBa * NFkB;
% params18 * IkBan * NFkBn = params18 * IkBan * NFkBn;
% params19 * IkBaNFkB = params19 * IkBaNFkB;
% params20 * IkBaNFkBn = params20 * IkBaNFkBn;
% params21 * IKK * IkBaNFkB = params21 * IKK * IkBaNFkB;
% params22 * IKK * IkBa = params22 * IKK * IkBa;
% params23 * IKKIkBaNFkB = params23 * IKKIkBaNFkB;
% params24 * IKKIkBa = params24 * IKKIkBa;
% params25 * IKKIkBaNFkB = params25 * IKKIkBaNFkB;
% params26 * IKKIkBa = params26 * IKKIkBa;
% params27 * LPS * CD14 = params27 * LPS * CD14;
% params28 * CD14LPS = params28 * CD14LPS;
% params29 = params29;
% params30 * CD14 = params30 * CD14;
% params31 * CD14LPS * TLR4 = params31 * CD14LPS * TLR4;
% params32 * TLR4LPS = params32 * TLR4LPS;
% params33 * CD14LPSen * TLR4en = params33 * CD14LPSen * TLR4en;
% params34 * TLR4LPSen = params34 * TLR4LPSen;
% params35 = params35;
% params36 * CD14LPS = params36 * CD14LPS;
% params37 * CD14LPSen = params37 * CD14LPSen;
% params38 * TLR4 = params38 * TLR4;
% params39 * TLR4en = params39 * TLR4en;
% params40 * TLR4LPS = params40 * TLR4LPS;
% params41 * TLR4LPSen = params41 * TLR4LPSen;
% params42 * CD14LPSen = params42 * CD14LPSen;
% params43 * TLR4en = params43 * TLR4en;
% params44 * TLR4LPSen = params44 * TLR4LPSen;
% params45 * (TLR4LPS.^params45n2)/( (TLR4LPS.^params45n2) + (params45n3.^params45n2) ) * MyD88_off = params45 * (TLR4LPS.^params45n2)/( (TLR4LPS.^params45n2) + (params45n3.^params45n2) ) * MyD88_off;
% params46 * MyD88 = params46 * MyD88;
% params47 * TRIF_off * TLR4LPSen = params47 * TRIF_off * TLR4LPSen;
% params48 * TRIF = params48 * TRIF;
% params49 * MyD88 * TRAF6_off = params49 * MyD88 * TRAF6_off;
% params50 * TRIF * TRAF6_off = params50 * TRIF * TRAF6_off;
% params51 * TRAF6 = params51 * TRAF6;
% params52 * TRAF6 * TAK1_off = params52 * TRAF6 * TAK1_off;
% params53 * TNF = params53 * TNF;
% params54 = params54;
% params55 * TNFR = params55 * TNFR;
% params56 * TNF * TNFR = params56 * TNF * TNFR;
% params57 * TNFR_TNF = params57 * TNFR_TNF;
% params58 * TNFR_TNF = params58 * TNFR_TNF;
% params59 * TNFR_TNF * TTR = params59 * TNFR_TNF * TTR;
% params60 * C1_off = params60 * C1_off;
% params61 * C1_off = params61 * C1_off;
% params62 * C1_off = params62 * C1_off;
% params63 * C1 = params63 * C1;
% params64 * C1 = params64 * C1;
% params65 * C1 * TAK1_off = params65 * C1 * TAK1_off;
% params66 * TAK1 = params66 * TAK1;
% params67 * (TAK1.^params67n2)/( (TAK1.^params67n2) + (params67n3.^params67n2) ) * IKK_off = params67 * (TAK1.^params67n2)/( (TAK1.^params67n2) + (params67n3.^params67n2) ) * IKK_off;
% params68 = params68;
% params69 * TLR2 = params69 * TLR2;
% params70 * Pam3CSK * CD14 = params70 * Pam3CSK * CD14;
% params71 * CD14_P3CSK = params71 * CD14_P3CSK;
% params72 * CD14_P3CSK * TLR2 = params72 * CD14_P3CSK * TLR2;
% params73 * CD14_P3CSK = params73 * CD14_P3CSK;
% params74 * TLR2_P3CSK = params74 * TLR2_P3CSK;
% params75 * TLR2_P3CSK = params75 * TLR2_P3CSK;
% params76 * (TLR2_P3CSK.^params76n2)/( (TLR2_P3CSK.^params76n2) + (params76n3.^params76n2) ) * MyD88_off = params76 * (TLR2_P3CSK.^params76n2)/( (TLR2_P3CSK.^params76n2) + (params76n3.^params76n2) ) * MyD88_off;
% params77 = params77;
% params78 * TLR3 = params78 * TLR3;
% params79 * (polyIC.^params79n3)/( (polyIC.^params79n3) + (params79n2.^params79n3) ) = params79 * (polyIC.^params79n3)/( (polyIC.^params79n3) + (params79n2.^params79n3) );
% params80 * polyIC_en = params80 * polyIC_en;
% params81 * polyIC_en * TLR3 = params81 * polyIC_en * TLR3;
% params82 * TLR3_polyIC = params82 * TLR3_polyIC;
% params83 * TLR3_polyIC = params83 * TLR3_polyIC;
% params84 * TRIF_off * TLR3_polyIC = params84 * TRIF_off * TLR3_polyIC;
% params85 = params85;
% params86 * TLR9 = params86 * TLR9;
% params87 * TLR9_N = params87 * TLR9_N;
% params88 * (CpG.^params88n3)/( (CpG.^params88n3) + (params88n2.^params88n3) ) = params88 * (CpG.^params88n3)/( (CpG.^params88n3) + (params88n2.^params88n3) );
% params89 * CpG_en = params89 * CpG_en;
% params90 * CpG_en * TLR9 = params90 * CpG_en * TLR9;
% params91 * TLR9_CpG = params91 * TLR9_CpG;
% params92 * TLR9_CpG * TLR9_N = params92 * TLR9_CpG * TLR9_N;
% params93 * TLR9_CpG = params93 * TLR9_CpG;
% params94 * (TLR9_CpG.^params94n2)/( (TLR9_CpG.^params94n2) + (params94n3.^params94n2) ) * MyD88_off = params94 * (TLR9_CpG.^params94n2)/( (TLR9_CpG.^params94n2) + (params94n3.^params94n2) ) * MyD88_off;
% params95 * NFkB = params95 * NFkB;
% params96 * IkBat = params96 * IkBat;
% params97 * IkBat_cas1 = params97 * IkBat_cas1;
% params98 * IkBat_cas2 = params98 * IkBat_cas2;
% params99 * NFkBn = params99 * NFkBn;
% params10 * NFkB0 = params99 * NFkBn_cas1;
% params10 * NFkB1 = params99 * NFkBn_cas2;

%% Section 5: Set species' deltas from reactions
delta(1) = 0;
delta(2) = - params9 * IkBa - params15 * IkBa - params17 * IkBa * NFkB - params22 * IKK * IkBa + params8 * IkBat_cas2 + (params11 * IkBan * params11n2) + params19 * IkBaNFkB + params24 * IKKIkBa;
delta(3) = - params11 * IkBan - params16 * IkBan - params18 * IkBan * NFkBn + (params9 * IkBa * params9n2) + params20 * IkBaNFkBn;
delta(4) = - params13 * IkBaNFkB - params19 * IkBaNFkB - params21 * IKK * IkBaNFkB + (params14 * IkBaNFkBn * params14n2) + params17 * IkBa * NFkB + params23 * IKKIkBaNFkB;
delta(5) = - params14 * IkBaNFkBn - params20 * IkBaNFkBn + (params13 * IkBaNFkB * params13n2) + params18 * IkBan * NFkBn;
delta(6) = params5 + params6 * (NFkBn_cas2.^params6n2)/( (NFkBn_cas2.^params6n2) + (params6n3.^params6n2) ) - params96 * IkBat; %- params7 * IkBat + 
delta(7) = - params23 * IKKIkBaNFkB - params25 * IKKIkBaNFkB + params21 * IKK * IkBaNFkB;
delta(8) = - params24 * IKKIkBa - params26 * IKKIkBa + params22 * IKK * IkBa;
delta(9) = - params10 * NFkB - params17 * IkBa * NFkB - params95 * NFkB + (params12 * NFkBn * params12n2) + params19 * IkBaNFkB + params25 * IKKIkBaNFkB;
delta(10) = - params12 * NFkBn - params18 * IkBan * NFkBn + (params10 * NFkB * params10n2) + params20 * IkBaNFkBn ;
delta(11) = - params1 * stim * IKK_off - params2 * IKK_off - params67 * (TAK1.^params67n2)/( (TAK1.^params67n2) + (params67n3.^params67n2) ) * IKK_off + params4 * IKK_i;
delta(12) = - params3 * IKK - params21 * IKK * IkBaNFkB - params22 * IKK * IkBa + params1 * stim * IKK_off + params2 * IKK_off + params23 * IKKIkBaNFkB + params24 * IKKIkBa + params25 * IKKIkBaNFkB + params26 * IKKIkBa + params67 * (TAK1.^params67n2)/( (TAK1.^params67n2) + (params67n3.^params67n2) ) * IKK_off;
delta(13) = - params4 * IKK_i + params3 * IKK;
delta(14) = - (params27 * LPS * CD14 * params27n2) + (params28 * CD14LPS * params28n2);
delta(15) = - params27 * LPS * CD14 - params30 * CD14 - params70 * Pam3CSK * CD14 + params28 * CD14LPS + params29 + params71 * CD14_P3CSK;
delta(16) = - params28 * CD14LPS - params31 * CD14LPS * TLR4 - params36 * CD14LPS + params27 * LPS * CD14 + params32 * TLR4LPS + params37 * CD14LPSen;
delta(17) = - params33 * CD14LPSen * TLR4en - params37 * CD14LPSen - params42 * CD14LPSen + params34 * TLR4LPSen + params36 * CD14LPS;
delta(18) = - params31 * CD14LPS * TLR4 - params38 * TLR4 + params32 * TLR4LPS + params35 + params39 * TLR4en;
delta(19) = - params33 * CD14LPSen * TLR4en - params39 * TLR4en - params43 * TLR4en + params34 * TLR4LPSen + params38 * TLR4;
delta(20) = - params32 * TLR4LPS - params40 * TLR4LPS + params31 * CD14LPS * TLR4 + params41 * TLR4LPSen;
delta(21) = - params34 * TLR4LPSen - params41 * TLR4LPSen - params44 * TLR4LPSen + params33 * CD14LPSen * TLR4en + params40 * TLR4LPS;
delta(22) = - params45 * (TLR4LPS.^params45n2)/( (TLR4LPS.^params45n2) + (params45n3.^params45n2) ) * MyD88_off - params76 * (TLR2_P3CSK.^params76n2)/( (TLR2_P3CSK.^params76n2) + (params76n3.^params76n2) ) * MyD88_off - params94 * (TLR9_CpG.^params94n2)/( (TLR9_CpG.^params94n2) + (params94n3.^params94n2) ) * MyD88_off + params46 * MyD88;
delta(23) = - params46 * MyD88 + params45 * (TLR4LPS.^params45n2)/( (TLR4LPS.^params45n2) + (params45n3.^params45n2) ) * MyD88_off + params76 * (TLR2_P3CSK.^params76n2)/( (TLR2_P3CSK.^params76n2) + (params76n3.^params76n2) ) * MyD88_off + params94 * (TLR9_CpG.^params94n2)/( (TLR9_CpG.^params94n2) + (params94n3.^params94n2) ) * MyD88_off;
delta(24) = - params47 * TRIF_off * TLR4LPSen - params84 * TRIF_off * TLR3_polyIC + params48 * TRIF;
delta(25) = - params48 * TRIF + params47 * TRIF_off * TLR4LPSen + params84 * TRIF_off * TLR3_polyIC;
delta(26) = - params49 * MyD88 * TRAF6_off - params50 * TRIF * TRAF6_off + params51 * TRAF6;
delta(27) = - params51 * TRAF6 + params49 * MyD88 * TRAF6_off + params50 * TRIF * TRAF6_off;
delta(28) = - params53 * TNF - (params56 * TNF * TNFR * params56n2) + (params57 * TNFR_TNF * params57n2);
delta(29) = - params55 * TNFR - params56 * TNF * TNFR + params54 + params57 * TNFR_TNF;
delta(30) = - params57 * TNFR_TNF - params58 * TNFR_TNF - params59 * TNFR_TNF * TTR + params56 * TNF * TNFR + params60 * C1_off;
delta(31) = - params59 * TNFR_TNF * TTR + params60 * C1_off;
delta(32) = - params60 * C1_off - params61 * C1_off - params62 * C1_off + params59 * TNFR_TNF * TTR + params63 * C1;
delta(33) = - params63 * C1 - params64 * C1 + params62 * C1_off;
delta(34) = - params52 * TRAF6 * TAK1_off - params65 * C1 * TAK1_off + params66 * TAK1;
delta(35) = - params66 * TAK1 + params52 * TRAF6 * TAK1_off + params65 * C1 * TAK1_off;
delta(36) = - (params70 * Pam3CSK * CD14 * params70n2) + (params71 * CD14_P3CSK * params71n2);
delta(37) = - params69 * TLR2 - params72 * CD14_P3CSK * TLR2 + params68 + params74 * TLR2_P3CSK;
delta(38) = - params71 * CD14_P3CSK - params72 * CD14_P3CSK * TLR2 - params73 * CD14_P3CSK + params70 * Pam3CSK * CD14 + params74 * TLR2_P3CSK;
delta(39) = - params74 * TLR2_P3CSK - params75 * TLR2_P3CSK + params72 * CD14_P3CSK * TLR2;
delta(40) = - (params79 * (polyIC.^params79n3)/( (polyIC.^params79n3) + (params79n2.^params79n3) ) * params79n4) + (params80 * polyIC_en * params80n2);
delta(41) = - params80 * polyIC_en - params81 * polyIC_en * TLR3 + params79 * (polyIC.^params79n3)/( (polyIC.^params79n3) + (params79n2.^params79n3) ) + params82 * TLR3_polyIC;
delta(42) = - params78 * TLR3 - params81 * polyIC_en * TLR3 + params77 + params82 * TLR3_polyIC;
delta(43) = - params82 * TLR3_polyIC - params83 * TLR3_polyIC + params81 * polyIC_en * TLR3;
delta(44) = - (params88 * (CpG.^params88n3)/( (CpG.^params88n3) + (params88n2.^params88n3) ) * params88n4) + (params89 * CpG_en * params89n2);
delta(45) = - params89 * CpG_en - params90 * CpG_en * TLR9 + params88 * (CpG.^params88n3)/( (CpG.^params88n3) + (params88n2.^params88n3) ) + params91 * TLR9_CpG;
delta(46) = - params86 * TLR9 - params90 * CpG_en * TLR9 + params85 + params91 * TLR9_CpG;
delta(47) = - params91 * TLR9_CpG - params92 * TLR9_CpG * TLR9_N - params93 * TLR9_CpG + params90 * CpG_en * TLR9;
delta(48) = - params87 * TLR9_N - params92 * TLR9_CpG * TLR9_N + params85;
delta(49) = params96 * IkBat - params97 * IkBat_cas1; %
delta(50) = params97 * IkBat_cas1 - params98 * IkBat_cas2;
delta(51) = params99 * NFkBn - params100 * NFkBn_cas1;
delta(52) = params100 * NFkBn_cas1 - params101 * NFkBn_cas2;
